# Generated by Django 3.2.8 on 2021-10-28 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('cohort', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('no_of_pages', models.IntegerField(default=10)),
                ('author', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isbn', models.CharField(blank=True, max_length=42, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
