# Generated by Django 3.2.8 on 2021-10-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
