# Generated by Django 3.2.8 on 2021-10-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20211026_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=300)),
                ('Last_name', models.CharField(max_length=300)),
                ('Age', models.IntegerField(default=10)),
                ('Course', models.CharField(max_length=300)),
                ('Bio', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
