# Generated by Django 3.2.8 on 2021-10-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20211028_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
