# Generated by Django 3.2.8 on 2021-10-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=300)),
                ('Last_name', models.CharField(max_length=300)),
                ('Age', models.IntegerField(default=10)),
                ('Course', models.CharField(max_length=300)),
                ('Bio', models.TextField()),
            ],
        ),
    ]
