# Generated by Django 3.2.8 on 2021-10-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
