# Generated by Django 3.2.8 on 2021-10-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isb',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
