# Generated by Django 3.2.8 on 2021-10-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20211028_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isb',
        ),
    ]
