# Generated by Django 3.2.8 on 2021-10-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
