# Generated by Django 3.2.9 on 2021-11-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
